# Generated by Django 6.0.3 on 2026-10-05 19:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_product_accepts_trade_product_trade_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Volta')),
                ('cash_payer', models.CharField(blank=True, choices=[('PROPOSER', 'Proponente'), ('OWNER', 'Anunciante')], max_length=8, verbose_name='Quem paga a volta')),
                ('status', models.CharField(choices=[('PENDING', 'Em negociação'), ('ACCEPTED', 'Aceita'), ('DECLINED', 'Recusada'), ('WITHDRAWN', 'Retirada'), ('EXPIRED', 'Expirada'), ('CANCELLED', 'Cancelada após o aceite')], default='PENDING', max_length=9, verbose_name='Status')),
                ('awaiting', models.CharField(choices=[('PROPOSER', 'Proponente'), ('OWNER', 'Anunciante')], default='OWNER', max_length=8, verbose_name='Aguardando resposta de')),
                ('rounds', models.PositiveIntegerField(default=1, verbose_name='Rodadas de negociação')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Encerrada em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_received', to=settings.AUTH_USER_MODEL, verbose_name='Anunciante')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_proposals', to='catalog.product', verbose_name='Anúncio')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades_proposed', to=settings.AUTH_USER_MODEL, verbose_name='Proponente')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_proposals', to='catalog.productvariant', verbose_name='Variação')),
            ],
            options={
                'verbose_name': 'Proposta de troca',
                'verbose_name_plural': 'Propostas de troca',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='TradeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('PROPOSED', 'Enviou a proposta'), ('COUNTERED', 'Fez uma contraproposta'), ('ACCEPTED', 'Aceitou a troca'), ('DECLINED', 'Recusou a proposta'), ('WITHDRAWN', 'Retirou a proposta'), ('EXPIRED', 'Proposta expirada sem resposta'), ('CANCELLED', 'Cancelou a troca')], max_length=9, verbose_name='Evento')),
                ('summary', models.TextField(blank=True, verbose_name='Termos')),
                ('message', models.TextField(blank=True, verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado em')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trades.tradeproposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Evento de troca',
                'verbose_name_plural': 'Eventos de troca',
                'ordering': ('created_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='TradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items', to='catalog.product', verbose_name='Anúncio')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_items', to='catalog.productvariant', verbose_name='Variação')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trades.tradeproposal', verbose_name='Proposta')),
            ],
            options={
                'verbose_name': 'Item oferecido',
                'verbose_name_plural': 'Itens oferecidos',
                'unique_together': {('proposal', 'variant')},
            },
        ),
    ]
