# Generated by Django 6.0.3 on 2026-10-02 18:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_platformconfig_home_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='seller_response_days',
            field=models.PositiveIntegerField(default=3, help_text='Após uma solicitação de devolução, o comprador só pode abrir disputa depois que esse prazo terminar sem solução', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prazo de resposta do vendedor antes de uma disputa (dias)'),
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disputes/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='orders.dispute', verbose_name='Disputa')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.disputemessage', verbose_name='Mensagem')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Enviada por')),
            ],
            options={
                'verbose_name': 'Evidência de disputa',
                'verbose_name_plural': 'Evidências de disputa',
                'ordering': ('created_at',),
            },
        ),
    ]
