# Generated by Django 6.0.3 on 2026-10-02 18:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_platformconfig_seller_response_days_disputeevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='escalation_window_days',
            field=models.PositiveIntegerField(default=7, help_text='Encerrado o prazo do vendedor, o comprador tem esse prazo para abrir disputa; depois disso, a solicitação de devolução é encerrada e o pedido é concluído', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prazo para o comprador abrir disputa (dias)'),
        ),
        migrations.AddField(
            model_name='platformconfig',
            name='return_reasons',
            field=models.TextField(default='Produto com defeito\nProduto diferente do anunciado\nProduto incompleto\nKey ou código digital inválido\nProduto chegou danificado\nDesisti da compra\nOutro', help_text='Um motivo por linha', verbose_name='Motivos de devolução'),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_category', models.CharField(max_length=100, verbose_name='Motivo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Solicitada em')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_request', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Solicitação de devolução',
                'verbose_name_plural': 'Solicitações de devolução',
            },
        ),
        migrations.CreateModel(
            name='ReturnRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='returns/', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='orders.returnrequest', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Imagem de solicitação de devolução',
                'verbose_name_plural': 'Imagens de solicitação de devolução',
                'ordering': ('created_at',),
            },
        ),
    ]
