# Generated by Django 6.0.3 on 2026-10-05 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_platformconfig_auction_payment_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfig',
            name='second_chance_window_days',
            field=models.PositiveIntegerField(default=60, help_text='Após o fim de um leilão não vendido ou não pago, o vendedor pode oferecer o item a outro participante dentro desse prazo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Prazo para enviar ofertas de segunda chance (dias)'),
        ),
    ]
